# Generated by Django 5.2 on 2025-04-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('health', 'Health'), ('lifestyle', 'Lifestyle'), ('travel', 'Travel')], default='tech', max_length=20),
        ),
    ]
